[2024-03-27 13:24:02,985] [sales_order.py] INFO Sales Data Sample -->    order_id  customer_id  product_id  quantity  price  order_date
0      2334            5          40         3  35.60  2022-06-21
1      6228            8          13         7  36.52  2023-03-08
2      7784            9          44         4  46.56  2023-04-22
3      6588            5          26         1  15.87  2022-10-23
4      5910            8          32        10  77.00  2022-10-05
[2024-03-27 13:24:02,997] [credentials.py] INFO Found credentials in shared credentials file: ~/.aws/credentials
[2024-03-27 13:24:03,046] [sales_order.py] CRITICAL Invalid endpoint: https://secretsmanager..amazonaws.com Error: ValueError Some Other Issue 
